increase storage retention to 30days
dapr/test-infra pull request #140
Opened 2022-07-14 00:14 UTC by tanvigour

Signed-off-by: tanvigour <tanvi.gour@gmail.com>

# Description

Change prometheus storage retention time to a month so that we get data for entire month for longhaul availability

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2022-07-14 00:15 UTC, tanvigour commented
@halspang : please review when you get a chance

2022-07-14 14:30 UTC, halspang requested changes
Should we do this for the regular longhaul as well?

2022-07-14 16:23 UTC, tanvigour commented on .github/workflows/dapr-longhaul-nightly.yml
> +          kubectl get namespace | grep ${{ env.DAPR_MONITORING }} || kubectl create namespace ${{ env.DAPR_MONITORING }} -set server.retention="30d"
Thanks for catching this, the location i added to in the workflow wasn't right, it should be during dapr-prom install, you can see the change to 30h in dapr-prom-prometheus-server pod after that

2022-07-20 00:56 UTC, tanvigour commented
@halspang : please review

2022-07-20 13:45 UTC, merged